/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_1.h"
#include "QuadDec_M1.h"
#include "Clock_PWM.h"
#include "M1_IN2_aliases.h"
#include "M1_IN2.h"
#include "M1_IN1_aliases.h"
#include "M1_IN1.h"
#include "Clock_QENC.h"
#include "M1_QA_aliases.h"
#include "M1_QA.h"
#include "M1_QB_aliases.h"
#include "M1_QB.h"
#include "M1_EN_aliases.h"
#include "M1_EN.h"
#include "M1_D1_aliases.h"
#include "M1_D1.h"
#include "M1_D2_aliases.h"
#include "M1_D2.h"
#include "timer_clock.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "Control_Reg_1.h"
#include "isr_speed.h"
#include "Timer_1.h"
#include "QuadDec_M1_Cnt16.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

