name: Lint

on: 
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'     # excludes main

jobs:
  clang-format:
    name: Run clang format
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
           ref: ${{ github.ref }}
           fetch-depth: 0

      - name: Install Dependencies
        run: sudo apt-get install -y clang-format

      - name: Run clang format
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true
          auto_fix: true
          clang_format_auto_fix: true
          clang_format_dir: firmware/