name: Lint

on: 
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'     # excludes main

jobs:
  clang-format:
    name: Run clang format
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
           ref: ${{ github.ref }}
           fetch-depth: 0

      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: './firmware'
          clangFormatVersion: 16
          inplace: True
            
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: James
          author_email: james@jamesnzl.xyz
          message: 'style(firmware): :art: format with clang-format'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}